name: Sync Files to GitBook

on:
  push:
    branches:
      - main  # main 브랜치에 변경사항이 있을 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. DOCS 폴더 준비
      - name: Prepare DOCS folder
        run: |
          mkdir -p DOCS

      # 3. README.md를 제외한 모든 파일을 DOCS 폴더로 이동
      - name: Move all files to DOCS
        run: |
          find . -mindepth 1 -maxdepth 1 \
          -not -name ".git" -not -name ".github" -not -name "DOCS" \
          -exec mv {} DOCS/ \;

      # 4. GitBook으로 DOCS 폴더 하위 파일 업로드
      - name: Sync DOCS folder to GitBook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
        run: |
          for file in DOCS/*; do
            curl -X POST \
              -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"files\": [
                  {
                    \"path\": \"${file}\",
                    \"title\": \"$(basename ${file})\"
                  }
                ]
              }" \
              https://api.gitbook.com/v1/spaces/$GITBOOK_SPACE_ID/content
          done
