name: Sync README to GitBook

on:
  push:
    branches:
      - main  # main 브랜치에 변경사항이 있을 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. GitBook으로 README.md 업로드
      - name: Sync README.md to GitBook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "files": [
                {
                  "path": "README.md",
                  "title": "Introduction"
                }
              ]
            }' \
            https://api.gitbook.com/v1/spaces/$GITBOOK_SPACE_ID/content
